# Gitlab application config file

# Email used for notification
# about new issues, comments
email:
  from: git@git.freezzo.com
  host: git.freezzo.com

# Git Hosting congiguration
git_host:
  system: gitolite
  admin_uri: git@git.freezzo.com:gitolite-admin
  base_path: /home/git/repositories/
  host: git.freezzo.com
  git_user: git
  # port: 22

# Git settings
# Use default values unless you understand it
git:
  # Max size of git object like commit, in bytes
  # This value can be increased if you have a very large commits
  git_max_size: 5242880 # 5.megabytes
  # Git timeout to read commit, in seconds
  git_timeout: 20
